language: python
dist: trusty
git:
  depth: 10

cache:
  apt: true
  directories:
  - ${HOME}/.smt_solvers/btor
  - ${HOME}/.smt_solvers/bdd
  - ${HOME}/.cache/pip
  - ${HOME}/python_bindings/all
  - ${HOME}/python_bindings/msat
  - ${HOME}/python_bindings/z3
  - ${HOME}/python_bindings/cvc4
  - ${HOME}/python_bindings/yices
  - ${HOME}/python_bindings/bdd
  - ${HOME}/python_bindings/picosat
  - ${HOME}/python_bindings/btor

addons:
  apt:
    packages:
    - python-setuptools
    - python-nose
    - python-pip
    - python-dev
    - make
    - build-essential
    - swig
    - libgmp-dev
    - autoconf
    - libtool
    - wget
    - curl
    - libboost-dev
    - python3-all-dev
    - libmpc-dev

python:
  - 3.6
  - 2.7
  - pypy


# Multiple envs will cause multiple build across multiple python versions.
# We test the following:
# 1. PySMT w/o solvers
# 2. PySMT with one solver at the time
#
env:
  matrix:
    - PYSMT_SOLVER="all"   PYSMT_GMPY="TRUE"
    - PYSMT_SOLVER="all"   PYSMT_GMPY="FALSE"
    - PYSMT_SOLVER="None"  PYSMT_GMPY="FALSE"   PYSMT_CYTHON="TRUE"
    - PYSMT_SOLVER="None"  PYSMT_GMPY="FALSE"   PYSMT_CYTHON="FALSE"
    - PYSMT_SOLVER="msat"  PYSMT_GMPY="FALSE"
    - PYSMT_SOLVER="z3"    PYSMT_GMPY="FALSE"
    - PYSMT_SOLVER="cvc4"  PYSMT_GMPY="FALSE"
    - PYSMT_SOLVER="yices" PYSMT_GMPY="FALSE"
    - PYSMT_SOLVER="bdd"   PYSMT_GMPY="FALSE"
    - PYSMT_SOLVER="picosat" PYSMT_GMPY="FALSE"
    - PYSMT_SOLVER="btor"  PYSMT_GMPY="FALSE"
    - PYSMT_SOLVER="msat_wrap" PYSMT_GMPY="FALSE"
    - PYSMT_SOLVER="z3_wrap"   PYSMT_GMPY="FALSE"

matrix:
  fast_finish: true

  exclude:
    - python: pypy
      env: PYSMT_SOLVER="all"   PYSMT_GMPY="TRUE"
    - python: pypy
      env: PYSMT_SOLVER="all"   PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="None"  PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="msat"  PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="z3"    PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="cvc4"  PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="yices" PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="bdd"   PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="picosat" PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="btor"  PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="msat_wrap" PYSMT_GMPY="FALSE"
    - python: pypy
      env: PYSMT_SOLVER="z3_wrap"   PYSMT_GMPY="FALSE"

install:
  - "./ci/travis_install.sh"

script:
  - "./ci/travis_script.sh"

after_success:
  - coveralls
#
